Fix: Use div64_s64 for 64-bit signed integer division
ARM32 requires use of div64_s64 rather than a division with 64-bit
signed integers because the helper invoked by the compiler is not
implemented in the kernel. This leads to this modpost error:

ERROR: modpost: "__aeabi_ldivmod"

Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Change-Id: I6c3ca8f0b79d70c622d94bba082f15cc53d0a02d