Add missing prototype for wrapper_get_pfnblock_flags_mask()
Fix the following error when building with '-Werror -Wmissing-prototypes':

wrapper/page_alloc.c:30:15: error: no previous prototype for ‘wrapper_get_pfnblock_flags_mask’ [-Werror=missing-prototypes]
   30 | unsigned long wrapper_get_pfnblock_flags_mask(const struct page *page,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I071ffc36fb5ec7b6b19adab9589c567e1b42c217
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>