Fix channel_backend lookup during `ring_buffer_flush_or_populate_packet`
Observed issue
==============

In LTTng-tools, `tests/regression/tools/snapshot/test_kernel` fails on
arm64 as follows:

    # ./tests/regression/tools/snapshots//../../../../src/bin/lttng/lttng -vvv snapshot record -s 3N2bTVDEX6zA7n9V
    DBG1 - 15:01:38.223118060 [156022/156022]: LSM cmd type: 'SNAPSHOT_RECORD' (24) (in send_session_msg() at lttng-ctl.cpp:127)
    Error: kernctl_buffer_flush_or_populate_packet failed (-22)
    Error: Snapshot channel failed
    Error: Snapshot record failed
    not ok 8 - Snapshot recorded
      ---
        duration_ms: 49.220920
      ...
    #   Failed test 'Snapshot recorded'
    #   in ./tests/regression/tools/snapshots//../../../utils/utils.sh:lttng_snapshot_record() at line 2277.

Cause
=====

The access check during
`_lttng_kernel_abi_ring_buffer_flush_or_populate_packet` fails. With
additional logging, the subbuf_size and access check details are as
follows:

    [1380623.309291] Setting chanb->subbuf_size chanb=00000000b2d8a11f, new_subbuf_size=4096, old_subbuf_size=0
    [1380623.674818] Setting chanb->subbuf_size chanb=0000000070996d7e, new_subbuf_size=1048576, old_subbuf_size=0
    [1380623.926696] Setting chanb->subbuf_size chanb=00000000cad441ac, new_subbuf_size=4096, old_subbuf_size=0
    [1380623.927703] Testing write access to pointer=00000000d6d21141 chanb=00000000866a32d7 subbuf_size=4294967296
    [1380623.927867] Testing write access to pointer=00000000d6d21141 chanb=00000000866a32d7 subbuf_size=4294967296
    [1380623.928026] Testing write access to pointer=00000000d6d21141 chanb=00000000866a32d7 subbuf_size=4294967296
    [1380623.928166] Testing write access to pointer=00000000d6d21141 chanb=00000000866a32d7 subbuf_size=4294967296

The subbuf_size is always 2^32, which is an unexpected value. On
x86_64, this doesn't seem to cause an issue, but on other
architectures the access check fails.

The underlying cause is that the `channel_backend` lookup is
incorrect.

`channel_get_private(buf->backend.chan);` returns the pointer stored in
the priv member of the channel's backend data.

Solution
========

Correctly fetch the channel_backend.

Known drawbacks
===============

None.

Change-Id: Ifdebf4838c782e62dddaace68bebbbfba24a0c30
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>