Fix missing override when CONFIG_COMPAT_OLD_SIGACTION is not defined
On both arm64 and x86_64, building lttng-modules with a kernel that
does not have `CONFIG_COMPAT_OLD_SIGACTION` defined results in a build
failure similar to the following:

    NOTE: make -j 64 KERNEL_SRC=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-source KERNELDIR=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-source KERNEL_PATH=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-source KERNEL_VERSION=6.12.23-yocto-standard CC=aarch64-poky-linux-gcc    -fuse-ld=bfd  -ffile-prefix-map=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18=/usr/src/debug/lttng-modules/2.13.18  -ffile-prefix-map=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18=/usr/src/debug/lttng-modules/2.13.18  -ffile-prefix-map=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/recipe-sysroot=  -ffile-prefix-map=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/recipe-sysroot-native=   -ffile-prefix-map=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-source=/usr/src/kernel  -ffile-prefix-map=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-build-artifacts=/usr/src/kernel  LD=aarch64-poky-linux-ld.bfd   AR=aarch64-poky-linux-ar  OBJCOPY=aarch64-poky-linux-objcopy  STRIP=aarch64-poky-linux-strip O=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-build-artifacts KBUILD_EXTRA_SYMBOLS=
    make -C /home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-source M=/home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src \
            CONFIG_LTTNG=m CONFIG_LTTNG_CLOCK_PLUGIN_TEST=m \
            KCPPFLAGS='' \
            modules
    make[1]: Entering directory '/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-source'
    make[2]: Entering directory '/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-build-artifacts'
      CC [M]  /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-ring-buffer-client-discard.o
      CC [M]  /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-ring-buffer-client-overwrite.o
      CC [M]  /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-ring-buffer-metadata-client.o
      CC [M]  /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-ring-buffer-client-mmap-discard.o
      CC [M]  /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-ring-buffer-client-mmap-overwrite.o
      CC [M]  /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-ring-buffer-metadata-mmap-client.o
    ...
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-syscalls-exit-compat-table.c:94:31: error: '__event_probe__compat_syscall_exit_sigaction' undeclared here (not in a function); did you mean '__event_probe__compat_syscall_exit_rt_sigaction'?
       94 |                 .event_func = __event_probe__compat_syscall_exit_##_template, \
          |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/../include/instrumentation/syscalls/headers/arm-32-syscalls_pointers.h:1894:1: note: in expansion of macro 'TRACE_SYSCALL_TABLE'
     1894 | TRACE_SYSCALL_TABLE(sigaction, sigaction, 67, 3)
          | ^~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-syscalls-exit-compat-table.c:96:27: error: '__event_fields___compat_syscall_exit_sigaction' undeclared here (not in a function); did you mean '__event_fields___compat_syscall_exit_rt_sigaction'?
       96 |                 .fields = __event_fields___compat_syscall_exit_##_template, \
          |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/../include/instrumentation/syscalls/headers/arm-32-syscalls_pointers.h:1894:1: note: in expansion of macro 'TRACE_SYSCALL_TABLE'
     1894 | TRACE_SYSCALL_TABLE(sigaction, sigaction, 67, 3)
          | ^~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-syscalls-exit-compat-table.c:97:26: error: '__event_desc___compat_syscall_exit_sigaction' undeclared here (not in a function); did you mean '__event_desc___compat_syscall_exit_rt_sigaction'?
       97 |                 .desc = &__event_desc___compat_syscall_exit_##_name, \
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/../include/instrumentation/syscalls/headers/arm-32-syscalls_pointers.h:1894:1: note: in expansion of macro 'TRACE_SYSCALL_TABLE'
     1894 | TRACE_SYSCALL_TABLE(sigaction, sigaction, 67, 3)
          | ^~~~~~~~~~~~~~~~~~~
    make[4]: *** [/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-source/scripts/Makefile.build:229: /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-syscalls-exit-compat-table.o] Error 1
    make[4]: *** Waiting for unfinished jobs....
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-syscalls-entry-compat-table.c:95:31: error: '__event_probe__compat_syscall_entry_sigaction' undeclared here (not in a function); did you mean '__event_probe__compat_syscall_entry_rt_sigaction'?
       95 |                 .event_func = __event_probe__compat_syscall_entry_##_template, \
          |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/../include/instrumentation/syscalls/headers/arm-32-syscalls_pointers.h:1894:1: note: in expansion of macro 'TRACE_SYSCALL_TABLE'
     1894 | TRACE_SYSCALL_TABLE(sigaction, sigaction, 67, 3)
          | ^~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-syscalls-entry-compat-table.c:97:27: error: '__event_fields___compat_syscall_entry_sigaction' undeclared here (not in a function); did you mean '__event_fields___compat_syscall_entry_rt_sigaction'?
       97 |                 .fields = __event_fields___compat_syscall_entry_##_template, \
          |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/../include/instrumentation/syscalls/headers/arm-32-syscalls_pointers.h:1894:1: note: in expansion of macro 'TRACE_SYSCALL_TABLE'
     1894 | TRACE_SYSCALL_TABLE(sigaction, sigaction, 67, 3)
          | ^~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-syscalls-entry-compat-table.c:98:26: error: '__event_desc___compat_syscall_entry_sigaction' undeclared here (not in a function); did you mean '__event_desc___compat_syscall_entry_rt_sigaction'?
       98 |                 .desc = &__event_desc___compat_syscall_entry_##_name, \
          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/../include/instrumentation/syscalls/headers/arm-32-syscalls_pointers.h:1894:1: note: in expansion of macro 'TRACE_SYSCALL_TABLE'
     1894 | TRACE_SYSCALL_TABLE(sigaction, sigaction, 67, 3)
          | ^~~~~~~~~~~~~~~~~~~
    make[4]: *** [/home/mcfrisk/src/base/repo/poky/build_test/tmp/work-shared/genericarm64/kernel-source/scripts/Makefile.build:229: /home/mcfrisk/src/base/repo/poky/build_test/tmp/work/genericarm64-poky-linux/lttng-modules/2.13.18/lttng-modules-2.13.18/src/lttng-syscalls-entry-compat-table.o] Error 1

This happens because `OVERRIDE_TABLE_32_sigaction` is not defined to
stop the macro from being defined.

At the same time, the definitions have been moved to an arch generic
header since `CONFIG_COMPAT_OLD_SIGACTION` applies to several
architectures, not just x86_64/arm64:

- arm64
- ppc64
- s390x
- sparc64
- x86_64

Fixes: https://bugs.lttng.org/issues/1426
Change-Id: I03515a3c7ae2fe01181fdc936d40cb6c15db03e3
Signed-off-by: Kienan Stewart <kstewart@efficios.com>
Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>