Introduce lttng-metadata-print.c
Rather than inlining helpers into both ctf 1.8 and ctf 2 metadata
generation compile units, compile them into their own object file.

This is not performance critical, so inlining is not useful, and it's
best to save space.

Moreover, this fixes an issue on powerpc:

src/lttng-modules/src/lttng-metadata-print.h:126:5: error: function ‘lttng_metadata_printf’ can never be inlined because it uses variable argument lists

Signed-off-by: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Change-Id: I0dbe41f15ff3846fac11932a11280b61b5e9fb86